# ----------- CONFIGURABLE START -----------
title:            "Good Lands"
description:      "Tabletop RPG Collective"
url:              https://goodlands.github.io # Site url, without a slash at the end.
signoff:          "Good Lands" # Your name
google_analytics: "UA-98111938-1"
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"